'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { apiClient } from '@aagam/utils';
import DashboardLayout from '@/components/DashboardLayout';
import { formatDate, formatPaise } from '@/components/subscriptions/SubscriptionPlanCard';
import { CalendarDays, Check, Clock3, Loader2, MapPin, ShieldCheck, WalletCards } from 'lucide-react';
import { useToast, getToastErrorMessage } from '@/components/ToastProvider';

const tomorrow = () => { const d=new Date(); d.setDate(d.getDate()+1); return d.toISOString().slice(0,10); };
const clock = (minute:number) => `${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`;
export default function SubscribeReviewPage() {
  const { planId }=useParams<{planId:string}>(); const router=useRouter(); const toast=useToast();
  const [plan,setPlan]=useState<any>(); const [addresses,setAddresses]=useState<any[]>([]); const [addressId,setAddressId]=useState(''); const [startDate,setStartDate]=useState(tomorrow()); const [method,setMethod]=useState('PERSONAL_HANDOVER'); const [dropToken,setDropToken]=useState(''); const [instructions,setInstructions]=useState(''); const [quote,setQuote]=useState<any>(); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false);
  useEffect(()=>{Promise.all([apiClient.get(`/subscriptions/plans/${encodeURIComponent(planId)}`),apiClient.get('/customer/addresses')]).then(([p,a])=>{setPlan(p.data);const rows=Array.isArray(a.data)?a.data:[];setAddresses(rows);setAddressId((rows.find((x:any)=>x.isDefault)||rows[0])?.id||'');}).catch(e=>toast.error(getToastErrorMessage(e,'Subscription review could not be loaded.'))).finally(()=>setLoading(false));},[planId]); // eslint-disable-line react-hooks/exhaustive-deps
  const payload=useMemo(()=>({addressId,startDate,deliveryMethod:method,deliveryWindowStartMinute:plan?.defaultWindowStartMinute,deliveryWindowEndMinute:plan?.defaultWindowEndMinute}),[addressId,startDate,method,plan]);
  useEffect(()=>{if(!addressId||!plan)return;apiClient.post(`/subscriptions/plans/${encodeURIComponent(planId)}/quote`,payload).then(r=>setQuote(r.data)).catch(e=>toast.error(getToastErrorMessage(e,'Please review the selected date, address and method.')));},[addressId,startDate,method,planId,plan]); // eslint-disable-line react-hooks/exhaustive-deps
  const submit=async()=>{if(method==='TRUSTED_DROP'&&dropToken.trim().length<6){toast.warning('Enter a secure drop-point token with at least six characters.');return;}setSubmitting(true);try{const response=await apiClient.post('/customer/subscriptions',{...payload,planId,trustedDropInstructions:instructions||undefined,dropPointToken:method==='TRUSTED_DROP'?dropToken:undefined},{headers:{'Idempotency-Key':`web-subscription:${Date.now()}:${crypto.randomUUID()}`}});toast.success(response.data?.confirmationMessage||'Subscription requested.');router.replace(`/shop/subscriptions/${response.data.id}`);}catch(e){toast.error(getToastErrorMessage(e,'Subscription could not be created.'));}finally{setSubmitting(false);}};
  if(loading)return <DashboardLayout allowedRole="CUSTOMER"><div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-9 w-9 animate-spin text-emerald-700"/></div></DashboardLayout>;
  if(!plan)return <DashboardLayout allowedRole="CUSTOMER"><div className="p-10 text-center">Plan unavailable.</div></DashboardLayout>;
  return <DashboardLayout allowedRole="CUSTOMER"><div className="mx-auto max-w-5xl p-4 sm:p-7"><div className="grid gap-6 lg:grid-cols-[1fr_360px]">
    <div className="space-y-5"><header><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Final check</p><h1 className="mt-2 text-3xl font-black text-slate-900">Review subscription</h1><p className="mt-2 text-slate-600">This request becomes active only after the required first or weekly verified cash collection.</p></header>
      <section className="rounded-[26px] bg-gradient-to-br from-emerald-800 to-teal-700 p-6 text-white"><div className="flex gap-4">{plan.imageUrl?<img src={plan.imageUrl} alt="" className="h-24 w-24 rounded-3xl bg-white object-contain"/>:null}<div><h2 className="text-2xl font-black">{plan.name}</h2><p className="mt-2 text-emerald-100">{plan.totalDeliveries} deliveries · {plan.fundingCycle==='WEEKLY'?'Weekly cash funding':'Full-plan funding'}</p><p className="mt-4 text-3xl font-black">{formatPaise(plan.pricePaise)}</p></div></div></section>
      <Section icon={<MapPin/>} title="Delivery address"><div className="grid gap-3 sm:grid-cols-2">{addresses.map(a=><button key={a.id} onClick={()=>setAddressId(a.id)} className={`min-h-24 rounded-2xl border p-4 text-left ${addressId===a.id?'border-emerald-600 bg-emerald-50 ring-2 ring-emerald-100':'border-slate-200 bg-white'}`}><div className="flex justify-between"><span className="font-black text-slate-900">{a.label||'Address'}</span>{addressId===a.id?<Check className="h-5 w-5 text-emerald-700"/>:null}</div><p className="mt-2 text-sm leading-5 text-slate-600">{a.line1}, {a.city}</p></button>)}</div>{!addresses.length?<p className="rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-800">Add a saved address before subscribing.</p>:null}</Section>
      <div className="grid gap-5 md:grid-cols-2"><Section icon={<CalendarDays/>} title="Start date"><input type="date" min={tomorrow()} value={startDate} onChange={e=>setStartDate(e.target.value)} className="min-h-12 w-full rounded-xl border border-slate-200 px-4 font-bold text-slate-800"/></Section><Section icon={<Clock3/>} title="Delivery window"><div className="flex min-h-12 items-center rounded-xl bg-slate-50 px-4 font-black text-slate-700">{clock(plan.defaultWindowStartMinute)} – {clock(plan.defaultWindowEndMinute)}</div></Section></div>
      <Section icon={<ShieldCheck/>} title="Handover proof">{[['PERSONAL_HANDOVER','Personal OTP','OTP and GPS at the customer'],['TRUSTED_DROP','Trusted drop','Geofence, secure token and proof'],['SECURITY_RECEPTION','Security / reception','OTP and named handover']].filter(([v])=>v==='PERSONAL_HANDOVER'?plan.allowPersonalHandover:v==='TRUSTED_DROP'?plan.allowTrustedDrop:plan.allowSecurityHandover).map(([value,label,copy])=><button key={value} onClick={()=>setMethod(value)} className={`mb-2 flex min-h-16 w-full items-center gap-3 rounded-2xl border p-4 text-left ${method===value?'border-emerald-600 bg-emerald-50':'border-slate-200'}`}><span className={`h-5 w-5 rounded-full border-2 p-1 ${method===value?'border-emerald-700':'border-slate-300'}`}>{method===value?<span className="block h-full w-full rounded-full bg-emerald-700"/>:null}</span><span><strong className="block text-slate-900">{label}</strong><small className="text-slate-500">{copy}</small></span></button>)}{method==='TRUSTED_DROP'?<div className="mt-4 grid gap-3"><input type="password" value={dropToken} onChange={e=>setDropToken(e.target.value)} placeholder="Secure drop-point token" className="min-h-12 rounded-xl border border-slate-200 px-4"/><textarea value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Milk box or doorstep instructions" className="min-h-24 rounded-xl border border-slate-200 p-4"/></div>:null}</Section>
    </div>
    <aside className="h-fit rounded-[26px] border border-slate-200 bg-white p-5 shadow-lg lg:sticky lg:top-6"><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-amber-600"/><h2 className="text-lg font-black text-slate-900">Cash funding</h2></div><div className="mt-5 space-y-4"><Summary label="First verified delivery" value={formatPaise(quote?.firstCashCollectionPaise??plan.pricePaise)} strong/><Summary label="Later funded deliveries" value="₹0"/><Summary label="Plan end" value={formatDate(quote?.endDate)}/><Summary label="Skip policy" value={plan.allowSkip?`Up to ${plan.maximumSkips}`:'Not available'}/></div><p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm font-bold leading-6 text-amber-900">{quote?.confirmationMessage||`Subscription requested — ${formatPaise(plan.pricePaise)} will be collected during the first verified delivery.`}</p><button disabled={!addressId||submitting} onClick={()=>void submit()} className="mt-5 flex min-h-14 w-full items-center justify-center rounded-2xl bg-emerald-700 px-5 font-black text-white disabled:opacity-50">{submitting?<Loader2 className="h-5 w-5 animate-spin"/>:'Request subscription'}</button></aside>
  </div></div></DashboardLayout>;
}
function Section({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="mb-4 flex items-center gap-2 text-lg font-black text-slate-900"><span className="text-emerald-700 [&>svg]:h-5 [&>svg]:w-5">{icon}</span>{title}</h2>{children}</section>}
function Summary({label,value,strong}:{label:string;value:string;strong?:boolean}){return <div className="flex items-start justify-between gap-4"><span className="text-sm text-slate-500">{label}</span><strong className={strong?'text-xl text-emerald-700':'text-sm text-slate-900'}>{value}</strong></div>}
