#!/bin/bash
set -e

echo "============================================"
echo " AAGAM E-commerce - Codespace Full Startup"
echo "============================================"

# --------------------------------------------------
# 1. Start system services (PostgreSQL + Redis)
# --------------------------------------------------
echo "[1/9] Installing and starting PostgreSQL and Redis..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq postgresql postgresql-client redis-server sudo 2>&1 | tail -3

service postgresql start
for i in 1 2 3 4 5; do
  pg_isready -q && break
  [ $i -eq 5 ] && { echo "PostgreSQL failed to start"; exit 1; }
  sleep 1
done

killall redis-server 2>/dev/null || true
rm -f /var/run/redis/redis-server.pid 2>/dev/null || true
redis-server --daemonize yes
for i in 1 2 3 4 5; do
  redis-cli ping 2>/dev/null | grep -q PONG && break
  [ $i -eq 5 ] && { echo "Redis failed to start"; exit 1; }
  sleep 1
done

# --------------------------------------------------
# 2. Create database
# --------------------------------------------------
echo "[2/9] Creating database..."
sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';" 2>/dev/null || true
sudo -u postgres psql -c "CREATE DATABASE aagam_ecom;" 2>/dev/null || true
DB_URL="postgresql://postgres:postgres@localhost:5432/aagam_ecom"

# --------------------------------------------------
# 3. Write .env from environment (Codespaces secrets)
# --------------------------------------------------
echo "[3/9] Writing .env from environment variables..."

cat > .env << ENVEOF
# Auto-generated by codespace-start.sh
NODE_ENV=development
DATABASE_URL=$DB_URL
REDIS_URL=redis://localhost:6379
JWT_SECRET=${JWT_SECRET:-dev-jwt-secret-not-for-production}
CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3001,http://localhost:3000}
ENVEOF

# Append each variable if set in the environment
# GitHub normalizes Codespaces secret names to UPPERCASE,
# so also try uppercase when the mixed-case name is not found.
for var in \
  GOOGLE_WEB_CLIENT_ID GOOGLE_ANDROID_CLIENT_ID \
  FIREBASE_PROJECT_ID FIREBASE_CLIENT_EMAIL FIREBASE_PRIVATE_KEY FIREBASE_SERVICE_ACCOUNT_JSON \
  R2_ENDPOINT R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY R2_BUCKET_NAME R2_PUBLIC_URL \
  SUPABASE_URL SUPABASE_ANON_KEY \
  UPLOAD_STORAGE_PROVIDER UPLOAD_PRIVATE_BASE_URL \
  PAYMENT_PROVIDER PAYMENT_PROVIDER_KEY \
  WEB_PUBLIC_URL API_PUBLIC_URL \
  ADMIN_EMAIL ADMIN_PASSWORD \
  CUSTOMER_EMAIL CUSTOMER_PASSWORD \
  Rider_EMAIL Rider_PASSWORD \
  STORE_EMAIL STORE_PASSWORD \
  MOBILE_APP_SCHEME \
  RAILWAY_PUBLIC_DOMAIN RAILWAY_PRIVATE_DOMAIN RAILWAY_STATIC_URL \
  RAILWAY_SERVICE_AAGAM_API_URL RAILWAY_SERVICE_AAGAM_WEB_URL
do
  val="${!var}"
  # Fallback: try uppercase (GitHub normalizes secret names)
  if [ -z "$val" ]; then
    upper=$(echo "$var" | tr '[:lower:]' '[:upper:]')
    [ "$upper" != "$var" ] && val="${!upper}"
  fi
  if [ -n "$val" ]; then
    echo "$var=$val" >> .env
  fi
done

echo "  -> .env written with env vars from secrets"

# --------------------------------------------------
# 4. Detect Codespace URLs
# --------------------------------------------------
echo "[4/9] Detecting Codespace public URLs..."
if [ -n "$CODESPACE_NAME" ] && [ -n "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
  API_URL="https://${CODESPACE_NAME}-4000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
  WEB_URL="https://${CODESPACE_NAME}-3001.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
  echo "API_PUBLIC_URL=$API_URL" >> .env
  echo "WEB_PUBLIC_URL=$WEB_URL" >> .env
  echo "CORS_ORIGINS=$WEB_URL,http://localhost:3001,http://localhost:3000" >> .env
  echo "  -> Public API: $API_URL"
  echo "  -> Public Web: $WEB_URL"
fi

# --------------------------------------------------
# 5. Install npm dependencies
# --------------------------------------------------
echo "[5/9] Installing npm dependencies..."
npm install --silent 2>&1 | tail -1

# --------------------------------------------------
# 6. Generate Prisma client & push schema
# --------------------------------------------------
echo "[6/9] Setting up database schema..."
cd packages/database
echo "DATABASE_URL=$DB_URL" > .env
npx prisma generate 2>&1 | tail -1
npx prisma db push --accept-data-loss 2>&1 | tail -1

# Seed data if seed script exists
if [ -f seed.js ]; then
  echo "  -> Seeding database..."
  node seed.js 2>&1 | tail -1
fi
cd ../..

# --------------------------------------------------
# 7. Build packages + API gateway
# --------------------------------------------------
echo "[7/9] Building project..."
npx turbo build --filter=@aagam/types --filter=@aagam/utils --filter=@aagam/database --filter=@aagam/api-gateway 2>&1 | tail -1

# Build worker service
echo "  -> Building worker service..."
npx turbo build --filter=@aagam/worker-service 2>&1 | tail -1

# Build admin dashboard
echo "  -> Building admin dashboard..."
npx turbo build --filter=@aagam/ui --filter=@aagam/admin-dashboard 2>&1 | tail -1

# --------------------------------------------------
# 8. Install PM2 globally
# --------------------------------------------------
echo "[8/9] Installing PM2..."
npm install -g pm2 2>&1 | tail -1

# --------------------------------------------------
# 9. Start all services with PM2
# --------------------------------------------------
echo "[9/9] Starting services with PM2..."
# Write apps config for PM2
cat > pm2-codespace.config.js << 'PM2EOF'
module.exports = {
  apps: [
    {
      name: "api-gateway",
      cwd: "./apps/api-gateway",
      script: "dist/src/main.js",
      env: { NODE_ENV: "development", PORT: 4000 }
    },
    {
      name: "admin-dashboard",
      cwd: "./apps/admin-dashboard",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3001",
      env: { NODE_ENV: "development" }
    },
    {
      name: "worker-service",
      cwd: "./apps/worker-service",
      script: "dist/index.js",
      env: { NODE_ENV: "development" }
    }
  ]
};
PM2EOF

pm2 start pm2-codespace.config.js
pm2 save --force

echo ""
echo "============================================"
echo " ALL SERVICES RUNNING"
echo "============================================"
echo ""
pm2 status
echo ""
echo "API Gateway:  http://localhost:4000"
echo "Admin Panel:  http://localhost:3001"
echo "Redis:        redis://localhost:6379"
echo "Postgres:     postgresql://postgres:postgres@localhost:5432/aagam_ecom"
echo ""
echo "PM2 commands:  pm2 status | pm2 logs | pm2 stop all"
