// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/analytics" | "/admin/delivery-exceptions" | "/admin/delivery-zones" | "/admin/dispatch" | "/admin/live-tracking" | "/admin/notifications" | "/admin/notifications/settings" | "/admin/orders" | "/admin/partner-applications" | "/admin/products" | "/admin/products/routing-weights" | "/admin/promotions" | "/admin/riders" | "/admin/route-planning" | "/admin/stores" | "/admin/subscriptions" | "/admin/support" | "/forgot-password" | "/login" | "/partner" | "/rider" | "/rider/availability" | "/rider/cod" | "/rider/delivery" | "/rider/earnings" | "/rider/history" | "/rider/notifications" | "/rider/notifications/settings" | "/rider/offers" | "/rider/performance" | "/rider/pickup" | "/rider/profile" | "/rider/runs" | "/rider/support" | "/shop" | "/shop/account" | "/shop/addresses" | "/shop/checkout" | "/shop/deals" | "/shop/delivery-code/[deliveryJobId]" | "/shop/notifications" | "/shop/notifications/settings" | "/shop/orders" | "/shop/orders/[id]" | "/shop/orders/[id]/feedback" | "/shop/phase6" | "/shop/products/[id]" | "/shop/reorder" | "/shop/subscribe/[planId]" | "/shop/subscriptions" | "/shop/subscriptions/[id]" | "/shop/support" | "/shop/wishlist" | "/signup" | "/store" | "/store/inventory" | "/store/notifications" | "/store/notifications/settings" | "/store/orders" | "/store/pickup-proof" | "/store/stores" | "/store/subscriptions"
type AppRouteHandlerRoutes = "/brand/aagam-mark"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin/products"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/delivery-exceptions": {}
  "/admin/delivery-zones": {}
  "/admin/dispatch": {}
  "/admin/live-tracking": {}
  "/admin/notifications": {}
  "/admin/notifications/settings": {}
  "/admin/orders": {}
  "/admin/partner-applications": {}
  "/admin/products": {}
  "/admin/products/routing-weights": {}
  "/admin/promotions": {}
  "/admin/riders": {}
  "/admin/route-planning": {}
  "/admin/stores": {}
  "/admin/subscriptions": {}
  "/admin/support": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/brand/aagam-mark": {}
  "/forgot-password": {}
  "/login": {}
  "/partner": {}
  "/rider": {}
  "/rider/availability": {}
  "/rider/cod": {}
  "/rider/delivery": {}
  "/rider/earnings": {}
  "/rider/history": {}
  "/rider/notifications": {}
  "/rider/notifications/settings": {}
  "/rider/offers": {}
  "/rider/performance": {}
  "/rider/pickup": {}
  "/rider/profile": {}
  "/rider/runs": {}
  "/rider/support": {}
  "/shop": {}
  "/shop/account": {}
  "/shop/addresses": {}
  "/shop/checkout": {}
  "/shop/deals": {}
  "/shop/delivery-code/[deliveryJobId]": { "deliveryJobId": string; }
  "/shop/notifications": {}
  "/shop/notifications/settings": {}
  "/shop/orders": {}
  "/shop/orders/[id]": { "id": string; }
  "/shop/orders/[id]/feedback": { "id": string; }
  "/shop/phase6": {}
  "/shop/products/[id]": { "id": string; }
  "/shop/reorder": {}
  "/shop/subscribe/[planId]": { "planId": string; }
  "/shop/subscriptions": {}
  "/shop/subscriptions/[id]": { "id": string; }
  "/shop/support": {}
  "/shop/wishlist": {}
  "/signup": {}
  "/store": {}
  "/store/inventory": {}
  "/store/notifications": {}
  "/store/notifications/settings": {}
  "/store/orders": {}
  "/store/pickup-proof": {}
  "/store/stores": {}
  "/store/subscriptions": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin/products": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
