// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(admin)/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/delivery-exceptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delivery-exceptions">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/delivery-exceptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/delivery-zones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delivery-zones">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/delivery-zones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/dispatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/dispatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/live-tracking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/live-tracking">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/live-tracking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/notifications/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/notifications/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/partner-applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/partner-applications">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/partner-applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/products/routing-weights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/routing-weights">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/products/routing-weights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/promotions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/promotions">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/promotions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/riders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/riders">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/riders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/route-planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/route-planning">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/route-planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/stores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stores">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/stores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(admin)/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/availability">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/cod/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/cod">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/cod/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/delivery">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/earnings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/earnings">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/earnings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/history">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/notifications/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/notifications/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/notifications/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/offers">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/performance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/performance">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/performance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/pickup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/pickup">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/pickup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/runs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/runs">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/runs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(rider)/rider/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rider/support">> = Specific
  const handler = {} as typeof import("../../src/app/(rider)/rider/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/account">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/addresses">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/deals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/deals">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/deals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/delivery-code/[deliveryJobId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/delivery-code/[deliveryJobId]">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/delivery-code/[deliveryJobId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/notifications/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/notifications/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/notifications/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/orders/[id]/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/orders/[id]/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/orders/[id]/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/orders">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/phase6/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/phase6">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/phase6/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/reorder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/reorder">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/reorder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/subscribe/[planId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/subscribe/[planId]">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/subscribe/[planId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/subscriptions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/subscriptions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/subscriptions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/support">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(shop)/shop/wishlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shop/wishlist">> = Specific
  const handler = {} as typeof import("../../src/app/(shop)/shop/wishlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(store)/store/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/(store)/store/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(store)/store/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(store)/store/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(store)/store/notifications/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/notifications/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(store)/store/notifications/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(store)/store/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/orders">> = Specific
  const handler = {} as typeof import("../../src/app/(store)/store/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(store)/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store">> = Specific
  const handler = {} as typeof import("../../src/app/(store)/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(store)/store/pickup-proof/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/pickup-proof">> = Specific
  const handler = {} as typeof import("../../src/app/(store)/store/pickup-proof/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(store)/store/stores/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/stores">> = Specific
  const handler = {} as typeof import("../../src/app/(store)/store/stores/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(store)/store/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(store)/store/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/partner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/partner">> = Specific
  const handler = {} as typeof import("../../src/app/partner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/brand/aagam-mark/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/brand/aagam-mark">> = Specific
  const handler = {} as typeof import("../../src/app/brand/aagam-mark/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(admin)/admin/products/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/(admin)/admin/products/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
