'use client';

import { useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { apiClient } from '@aagam/utils';
import DashboardLayout from '@/components/DashboardLayout';
import { formatDate, formatPaise } from '@/components/subscriptions/SubscriptionPlanCard';
import { CalendarDays, CheckCircle2, Loader2, MapPin, Pause, Play, ReceiptIndianRupee, Route, SkipForward, TriangleAlert, WalletCards } from 'lucide-react';
import { useToast, getToastErrorMessage } from '@/components/ToastProvider';

export default function SubscriptionDetailsPage(){const {id}=useParams<{id:string}>();const router=useRouter();const toast=useToast();const [s,setS]=useState<any>();const [deliveries,setDeliveries]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');
  const load=async()=>{try{const [a,b]=await Promise.all([apiClient.get(`/customer/subscriptions/${encodeURIComponent(id)}`),apiClient.get(`/customer/subscriptions/${encodeURIComponent(id)}/deliveries`)]);setS(a.data);setDeliveries(Array.isArray(b.data)?b.data:[]);}catch(e){toast.error(getToastErrorMessage(e,'Subscription could not be loaded.'));}finally{setLoading(false);}};useEffect(()=>{void load()},[id]); // eslint-disable-line react-hooks/exhaustive-deps
  const total=Number(s?.planVersion?.totalDeliveries||deliveries.length||1);const progress=Math.min(100,Math.round(Number(s?.completedDeliveries||0)/total*100));const next=useMemo(()=>deliveries.find(d=>['SCHEDULED','ORDER_GENERATED','PREPARING','PACKED','ASSIGNED','OUT_FOR_DELIVERY'].includes(d.status)),[deliveries]);
  const action=async(kind:'skip'|'pause'|'resume')=>{setBusy(kind);try{if(kind==='skip'){if(!next||next.status!=='SCHEDULED')throw new Error('No skippable future delivery is available.');await apiClient.post(`/customer/subscriptions/${id}/deliveries/${next.id}/skip`,{reason:'Customer requested skip'},{headers:{'Idempotency-Key':`web-skip:${crypto.randomUUID()}`}});}else if(kind==='pause'){const d=new Date();d.setDate(d.getDate()+1);await apiClient.post(`/customer/subscriptions/${id}/pause`,{effectiveFrom:d.toISOString(),reason:'Customer requested pause'},{headers:{'Idempotency-Key':`web-pause:${crypto.randomUUID()}`}});}else await apiClient.post(`/customer/subscriptions/${id}/resume`,{},{headers:{'Idempotency-Key':`web-resume:${crypto.randomUUID()}`}});toast.success(kind==='skip'?'Delivery skipped':kind==='pause'?'Subscription paused':'Subscription resumed');await load();}catch(e){toast.error(getToastErrorMessage(e,'Action failed.'));}finally{setBusy('')}};
  const track=async()=>{try{const {data}=await apiClient.get(`/customer/subscriptions/${id}/tracking`);if(data?.orderId)router.push(`/shop/orders?orderId=${data.orderId}`);else toast.info('No active delivery order is available yet.');}catch(e){toast.error(getToastErrorMessage(e,'Tracking is unavailable.'))}};
  if(loading)return <DashboardLayout allowedRole="CUSTOMER"><div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-9 w-9 animate-spin text-emerald-700"/></div></DashboardLayout>;if(!s)return <DashboardLayout allowedRole="CUSTOMER"><div className="p-10 text-center">Subscription not found.</div></DashboardLayout>;
  return <DashboardLayout allowedRole="CUSTOMER"><div className="mx-auto max-w-6xl space-y-5 p-4 sm:p-7"><section className="rounded-[30px] bg-gradient-to-br from-emerald-800 to-teal-700 p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-200">{String(s.status).replaceAll('_',' ')}</p><h1 className="mt-3 text-3xl font-black">{s.plan?.name}</h1><p className="mt-2 text-emerald-100">{s.fundingCycle==='WEEKLY'?'Weekly cash funding':'Full-plan cash funding'} · {String(s.deliveryMethod).replaceAll('_',' ')}</p></div><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full border-[10px] border-emerald-300/60 bg-emerald-900/20"><strong className="text-2xl">{progress}%</strong><span className="text-xs text-emerald-100">complete</span></div></div><div className="mt-6 h-3 overflow-hidden rounded-full bg-white/20"><div className="h-full rounded-full bg-white" style={{width:`${progress}%`}}/></div><div className="mt-4 flex flex-wrap justify-between gap-4 text-sm font-bold text-emerald-100"><span>{s.completedDeliveries} of {total} delivered</span><span>{s.remainingFundedDeliveries} funded deliveries left</span><span>{s.skippedDeliveries} skipped</span></div></section>
    <section className="grid gap-4 md:grid-cols-[1fr_auto]"><div className="rounded-[24px] border border-slate-200 bg-white p-5"><div className="flex items-start gap-4"><span className="rounded-2xl bg-amber-600 p-3 text-white"><CalendarDays className="h-6 w-6"/></span><div><p className="text-xs font-black uppercase tracking-wider text-amber-700">Next delivery</p><h2 className="mt-1 text-2xl font-black text-slate-900">{formatDate(next?.serviceDate||s.nextDeliveryDate)}</h2><p className="mt-1 text-sm font-bold text-slate-500">{next?.cashDuePaise>0?`Cash due ${formatPaise(next.cashDuePaise)}`:'Subscription already funded · Customer amount due ₹0'}</p></div></div></div><button onClick={()=>void track()} className="flex min-h-24 items-center justify-center gap-2 rounded-[24px] bg-emerald-100 px-8 font-black text-emerald-800"><Route className="h-5 w-5"/>Track current order</button></section>
    <section className="grid grid-cols-3 gap-3"><Action icon={<SkipForward/>} label="Skip next" disabled={busy!==''||s.status==='PAUSED'} onClick={()=>void action('skip')}/>{s.status==='PAUSED'?<Action icon={<Play/>} label="Resume" disabled={busy!==''} onClick={()=>void action('resume')}/>:<Action icon={<Pause/>} label="Pause" disabled={busy!==''} onClick={()=>void action('pause')}/>}<Action icon={<TriangleAlert/>} label="Report issue" onClick={()=>router.push('/shop/support')}/></section>
    <div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-xl font-black text-slate-900">Delivery calendar & history</h2><div className="mt-4 divide-y divide-slate-100">{deliveries.map(d=><div key={d.id} className="flex items-center gap-4 py-4"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${d.status==='DELIVERED'?'bg-emerald-600 text-white':d.status==='SKIPPED'?'bg-amber-100 text-amber-700':'bg-slate-100 text-slate-500'}`}>{d.status==='DELIVERED'?<CheckCircle2 className="h-5 w-5"/>:<CalendarDays className="h-4 w-4"/>}</span><div className="min-w-0 flex-1"><strong className="text-slate-900">{formatDate(d.serviceDate)}</strong><p className="mt-1 text-xs font-bold uppercase text-slate-400">Day {d.sequenceNumber} · {String(d.status).replaceAll('_',' ')}</p></div><strong className={d.cashDuePaise>0?'text-amber-700':'text-emerald-700'}>{formatPaise(d.cashDuePaise)}</strong></div>)}</div></section><aside className="space-y-5"><section className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-lg font-black text-slate-900">Preferences</h2><Info icon={<MapPin/>} label="Address" value={s.address?.label||'Saved address'}/><Info icon={<WalletCards/>} label="Funding" value={s.fundingCycle==='WEEKLY'?'Every seven deliveries':'First verified delivery'}/><Info icon={<ReceiptIndianRupee/>} label="Amount collected" value={formatPaise(s.amountCollectedPaise)}/></section>{s.fundingAllocations?.length?<section className="rounded-[24px] border border-slate-200 bg-white p-5"><h2 className="text-lg font-black text-slate-900">Funding receipts</h2>{s.fundingAllocations.map((a:any)=><div key={a.id} className="mt-3 rounded-2xl bg-emerald-50 p-4"><strong className="text-emerald-800">{formatPaise(a.amountPaise)} received</strong><p className="mt-1 text-xs text-emerald-700">Deliveries {a.startsAtSequence}–{a.endsAtSequence} · {formatDate(a.createdAt)}</p></div>)}</section>:null}</aside></div>
  </div></DashboardLayout>}
function Action({icon,label,onClick,disabled}:{icon:React.ReactNode;label:string;onClick:()=>void;disabled?:boolean}){return <button disabled={disabled} onClick={onClick} className="flex min-h-20 flex-col items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white font-black text-slate-700 hover:border-emerald-300 disabled:opacity-50"><span className="text-emerald-700 [&>svg]:h-5 [&>svg]:w-5">{icon}</span>{label}</button>}
function Info({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="mt-4 flex items-center gap-3 border-t border-slate-100 pt-4"><span className="text-emerald-700 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><p className="text-xs font-bold uppercase text-slate-400">{label}</p><p className="mt-1 text-sm font-black capitalize text-slate-800">{value}</p></div></div>}
