ALTER TYPE "PromotionPlacement" ADD VALUE IF NOT EXISTS 'LANDING_HERO';
ALTER TYPE "PromotionPlacement" ADD VALUE IF NOT EXISTS 'LANDING_BANNER';
ALTER TYPE "PromotionPlacement" ADD VALUE IF NOT EXISTS 'LOGIN_SIDEBAR';
