-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'STORE_DELIVERING';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'STORE_DELIVERED';

-- AlterTable
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "storeDelivery" BOOLEAN NOT NULL DEFAULT false;
