#!/usr/bin/env bash
set -euo pipefail

app_slug="${1:?app slug is required}"
package_name="${2:?package name is required}"
google_services_path="${3:?google-services.json path is required}"
validator_path="${4:?validator path is required}"
proof_dir="${5:-release-proof}"
proof_file="$proof_dir/${app_slug}-google-signin-proof.md"

mkdir -p "$(dirname "$google_services_path")" "$proof_dir"

{
  echo "# ${app_slug^} Google Sign-In proof"
  echo
  echo "- Package: \`$package_name\`"
  echo "- Generated by workflow run: \`${GITHUB_RUN_ID:-unknown}\`"
  echo "- Commit: \`${RELEASE_SHA:-${GITHUB_SHA:-unknown}}\`"
} > "$proof_file"

fail() {
  local message="$1"
  {
    echo "- Result: \`FAILED\`"
    echo
    echo "## Failure"
    echo '```text'
    echo "$message"
    echo '```'
  } >> "$proof_file"
  echo "::error::$message"
  exit 1
}

missing=()
for name in GOOGLE_WEB_CLIENT_ID GOOGLE_ANDROID_CLIENT_ID GOOGLE_SERVICES_JSON; do
  if [[ -z "${!name:-}" ]]; then
    missing+=("$name")
  fi
done
if (( ${#missing[@]} > 0 )); then
  fail "Missing required GitHub configuration for $app_slug: ${missing[*]}"
fi

if ! printf '%s' "$GOOGLE_SERVICES_JSON" > "$google_services_path"; then
  fail "Could not write $google_services_path"
fi

release_values=(
  "${KEYSTORE_BASE64:-}"
  "${AAGAM_ANDROID_KEYSTORE_PASSWORD:-}"
  "${AAGAM_ANDROID_KEY_ALIAS:-}"
  "${AAGAM_ANDROID_KEY_PASSWORD:-}"
)
configured=0
for value in "${release_values[@]}"; do
  [[ -n "$value" ]] && configured=$((configured + 1))
done
if (( configured > 0 && configured < 4 )); then
  fail "Android release signing secrets must be configured together: ANDROID_KEYSTORE_BASE64, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD"
fi

if (( configured == 4 )); then
  signing_store="${RUNNER_TEMP:?RUNNER_TEMP is required}/aagam-release.keystore"
  if ! printf '%s' "$KEYSTORE_BASE64" | base64 --decode > "$signing_store"; then
    fail "ANDROID_KEYSTORE_BASE64 is not valid base64"
  fi
  signing_alias="$AAGAM_ANDROID_KEY_ALIAS"
  signing_store_password="$AAGAM_ANDROID_KEYSTORE_PASSWORD"
  signing_channel="release"
  echo "AAGAM_ANDROID_KEYSTORE_PATH=$signing_store" >> "$GITHUB_ENV"
else
  if [[ -z "${DEBUG_KEYSTORE_BASE64:-}" ]]; then
    fail "No release keystore is configured and DEBUG_KEYSTORE_BASE64 is missing. An ephemeral certificate is forbidden because Google Sign-In would fail on the produced APK."
  fi
  signing_store="$HOME/.android/debug.keystore"
  mkdir -p "$HOME/.android"
  if ! printf '%s' "$DEBUG_KEYSTORE_BASE64" | base64 --decode > "$signing_store"; then
    fail "DEBUG_KEYSTORE_BASE64 is not valid base64"
  fi
  signing_alias="androiddebugkey"
  signing_store_password="android"
  signing_channel="pinned-debug"
fi

signing_sha1="$(keytool -list -v -keystore "$signing_store" -alias "$signing_alias" -storepass "$signing_store_password" 2>/dev/null | awk '/SHA1:/{print $2; exit}' || true)"
signing_sha256="$(keytool -list -v -keystore "$signing_store" -alias "$signing_alias" -storepass "$signing_store_password" 2>/dev/null | awk '/SHA256:/{print $2; exit}' || true)"
if [[ -z "$signing_sha1" || -z "$signing_sha256" ]]; then
  fail "Could not read SHA fingerprints from the configured Android keystore. Verify the keystore, alias, and passwords."
fi

{
  echo "- Signing channel: \`$signing_channel\`"
  echo "- APK signing SHA-1: \`$signing_sha1\`"
  echo "- APK signing SHA-256: \`$signing_sha256\`"
  echo "- Web OAuth client configured: yes"
  echo "- Android OAuth client configured: yes"
  echo "- google-services.json supplied: yes"
  echo
  echo "## Validation"
  echo '```text'
} >> "$proof_file"

set +e
validation_output="$({
  EXPECTED_PACKAGE_NAME="$package_name" \
  SIGNING_CERT_SHA1="$signing_sha1" \
  GOOGLE_SERVICES_JSON_PATH="$google_services_path" \
  node "$validator_path"
} 2>&1)"
validation_status=$?
set -e

printf '%s\n' "$validation_output" | tee -a "$proof_file"
echo '```' >> "$proof_file"

if (( validation_status != 0 )); then
  echo "- Result: \`FAILED\`" >> "$proof_file"
  echo "::error::$validation_output"
  exit "$validation_status"
fi

echo "- Result: \`PASSED\`" >> "$proof_file"
echo "Validated $app_slug Google Sign-In against APK signing SHA-1 $signing_sha1"
