#!/usr/bin/env bash
set -euo pipefail

app_slug="${1:?app slug is required}"
package_name="${2:?package name is required}"
google_services_path="${3:?google-services.json path is required}"
validator_path="${4:?validator path is required}"
proof_dir="${5:-release-proof}"
proof_file="$proof_dir/${app_slug}-google-signin-proof.md"

mkdir -p "$(dirname "$google_services_path")" "$proof_dir"

{
  echo "# ${app_slug^} Google Sign-In proof"
  echo
  echo "- Package: \`$package_name\`"
  echo "- Generated by workflow run: \`${GITHUB_RUN_ID:-unknown}\`"
  echo "- Commit: \`${RELEASE_SHA:-${GITHUB_SHA:-unknown}}\`"
} > "$proof_file"

fail() {
  local message="$1"
  {
    echo "- Result: \`FAILED\`"
    echo
    echo "## Failure"
    echo '```text'
    echo "$message"
    echo '```'
  } >> "$proof_file"
  echo "::error::$message"
  exit 1
}

release_values=(
  "${KEYSTORE_BASE64:-}"
  "${AAGAM_ANDROID_KEYSTORE_PASSWORD:-}"
  "${AAGAM_ANDROID_KEY_ALIAS:-}"
  "${AAGAM_ANDROID_KEY_PASSWORD:-}"
)
configured=0
for value in "${release_values[@]}"; do
  [[ -n "$value" ]] && configured=$((configured + 1))
done
if (( configured > 0 && configured < 4 )); then
  fail "Android release signing secrets must be configured together: ANDROID_KEYSTORE_BASE64, ANDROID_KEYSTORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD"
fi

if (( configured == 4 )); then
  signing_store="${RUNNER_TEMP:?RUNNER_TEMP is required}/aagam-release.keystore"
  if ! printf '%s' "$KEYSTORE_BASE64" | base64 --decode > "$signing_store"; then
    fail "ANDROID_KEYSTORE_BASE64 is not valid base64"
  fi
  signing_alias="$AAGAM_ANDROID_KEY_ALIAS"
  signing_store_password="$AAGAM_ANDROID_KEYSTORE_PASSWORD"
  signing_channel="release"
  echo "AAGAM_ANDROID_KEYSTORE_PATH=$signing_store" >> "$GITHUB_ENV"
else
  if [[ -z "${DEBUG_KEYSTORE_BASE64:-}" ]]; then
    fail "No release keystore is configured and DEBUG_KEYSTORE_BASE64 is missing. An ephemeral certificate is forbidden because Google Sign-In would fail on the produced APK."
  fi
  signing_store="$HOME/.android/debug.keystore"
  mkdir -p "$HOME/.android"
  if ! printf '%s' "$DEBUG_KEYSTORE_BASE64" | base64 --decode > "$signing_store"; then
    fail "DEBUG_KEYSTORE_BASE64 is not valid base64"
  fi
  signing_alias="androiddebugkey"
  signing_store_password="android"
  signing_channel="pinned-debug"
fi

signing_sha1="$(keytool -list -v -keystore "$signing_store" -alias "$signing_alias" -storepass "$signing_store_password" 2>/dev/null | awk '/SHA1:/{print $2; exit}' || true)"
signing_sha256="$(keytool -list -v -keystore "$signing_store" -alias "$signing_alias" -storepass "$signing_store_password" 2>/dev/null | awk '/SHA256:/{print $2; exit}' || true)"
if [[ -z "$signing_sha1" || -z "$signing_sha256" ]]; then
  fail "Could not read SHA fingerprints from the configured Android keystore. Verify the keystore, alias, and passwords."
fi

web_configured=no
android_configured=no
firebase_configured=no
[[ -n "${GOOGLE_WEB_CLIENT_ID:-}" ]] && web_configured=yes
[[ -n "${GOOGLE_ANDROID_CLIENT_ID:-}" ]] && android_configured=yes
[[ -n "${GOOGLE_SERVICES_JSON:-}" ]] && firebase_configured=yes

{
  echo "- Signing channel: \`$signing_channel\`"
  echo "- APK signing SHA-1: \`$signing_sha1\`"
  echo "- APK signing SHA-256: \`$signing_sha256\`"
  echo "- Web OAuth client configured: $web_configured"
  echo "- Android OAuth client configured: $android_configured"
  echo "- google-services.json supplied: $firebase_configured"
} >> "$proof_file"

missing=()
for name in GOOGLE_WEB_CLIENT_ID GOOGLE_ANDROID_CLIENT_ID GOOGLE_SERVICES_JSON; do
  if [[ -z "${!name:-}" ]]; then
    missing+=("$name")
  fi
done
if (( ${#missing[@]} > 0 )); then
  fail "Missing required GitHub configuration for $app_slug: ${missing[*]}"
fi

set +e
normalization_output="$(GOOGLE_SERVICES_JSON="$GOOGLE_SERVICES_JSON" node - "$google_services_path" <<'NODE' 2>&1
const fs = require('node:fs');
const path = require('node:path');

const outputPath = process.argv[2];
const raw = process.env.GOOGLE_SERVICES_JSON || '';
const candidates = [];
const seen = new Set();

function addCandidate(label, value) {
  if (typeof value !== 'string') return;
  const normalized = value.trim();
  if (!normalized || seen.has(normalized)) return;
  seen.add(normalized);
  candidates.push({ label, value: normalized });
}

const trimmed = raw.trim().replace(/^\uFEFF/, '');
addCandidate('raw', trimmed);

if (trimmed.startsWith("'") && trimmed.endsWith("'")) {
  addCandidate('single-quoted-wrapper', trimmed.slice(1, -1));
}

try {
  const decoded = JSON.parse(trimmed);
  if (typeof decoded === 'string') addCandidate('json-string', decoded);
} catch {
  // The secret may be shell-escaped or PowerShell-formatted rather than a JSON string.
}

const escapedJson = trimmed
  .replace(/\\r\\n/g, '\n')
  .replace(/\\n/g, '\n')
  .replace(/\\r/g, '\r')
  .replace(/\\t/g, '\t')
  .replace(/\\u0022/gi, '"')
  .replace(/`"/g, '"')
  .replace(/\\"/g, '"');
addCandidate('escaped-json', escapedJson);

const singleQuotedJson = escapedJson.replace(/'/g, '"');
addCandidate('single-quoted-json', singleQuotedJson);
addCandidate(
  'powershell-object-json',
  singleQuotedJson.replace(
    /([{,]\s*)([A-Za-z_$][A-Za-z0-9_$-]*)(\s*:)/g,
    '$1"$2"$3'
  )
);

if (/^[A-Za-z0-9+/=\r\n]+$/.test(trimmed)) {
  addCandidate('base64', Buffer.from(trimmed.replace(/\s+/g, ''), 'base64').toString('utf8'));
}

const failures = [];
for (const candidate of candidates) {
  try {
    const parsed = JSON.parse(candidate.value);
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      throw new Error('top-level value must be a JSON object');
    }
    if (!parsed.project_info || !Array.isArray(parsed.client)) {
      throw new Error('missing Firebase project_info or client array');
    }
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, `${JSON.stringify(parsed, null, 2)}\n`, { mode: 0o600 });
    console.log(`Normalized google-services.json from ${candidate.label} secret format.`);
    process.exit(0);
  } catch (error) {
    failures.push(`${candidate.label}: ${error.message}`);
  }
}

console.error('GOOGLE_SERVICES_JSON could not be normalized as Firebase JSON.');
for (const failure of failures) console.error(`- ${failure}`);
process.exit(1);
NODE
)"
normalization_status=$?
set -e

if (( normalization_status != 0 )); then
  fail "$normalization_output"
fi

echo "$normalization_output"
{
  echo
  echo "## Validation"
  echo '```text'
} >> "$proof_file"

set +e
validation_output="$({
  EXPECTED_PACKAGE_NAME="$package_name" \
  SIGNING_CERT_SHA1="$signing_sha1" \
  GOOGLE_SERVICES_JSON_PATH="$google_services_path" \
  node "$validator_path"
} 2>&1)"
validation_status=$?
set -e

printf '%s\n' "$validation_output" | tee -a "$proof_file"
echo '```' >> "$proof_file"

if (( validation_status != 0 )); then
  echo "- Result: \`FAILED\`" >> "$proof_file"
  echo "::error::$validation_output"
  exit "$validation_status"
fi

echo "- Result: \`PASSED\`" >> "$proof_file"
echo "Validated $app_slug Google Sign-In against APK signing SHA-1 $signing_sha1"
