'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { apiClient } from '@aagam/utils';
import DashboardLayout from '@/components/DashboardLayout';
import SubscriptionPlanCard, { formatDate, formatPaise } from '@/components/subscriptions/SubscriptionPlanCard';
import { CalendarClock, ChevronRight, Loader2, PauseCircle, Plus, RefreshCw, WalletCards } from 'lucide-react';
import { useToast, getToastErrorMessage } from '@/components/ToastProvider';

const segments: Record<string, string[]> = { Active: ['ACTIVE','PAYMENT_DUE','GRACE_PERIOD'], Upcoming: ['PENDING_CASH_COLLECTION'], Paused: ['PAUSED'], Completed: ['COMPLETED','CANCELLED'] };

export default function CustomerSubscriptionsPage() {
  const toast = useToast();
  const [plans, setPlans] = useState<any[]>([]); const [subscriptions, setSubscriptions] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [segment, setSegment] = useState('Active');
  const load = async () => { setLoading(true); try { const [p,s] = await Promise.all([apiClient.get('/subscriptions/plans'), apiClient.get('/customer/subscriptions')]); setPlans(Array.isArray(p.data) ? p.data : []); setSubscriptions(Array.isArray(s.data) ? s.data : []); } catch (error) { toast.error(getToastErrorMessage(error, 'Subscriptions could not be loaded.')); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered = useMemo(() => subscriptions.filter((item) => segments[segment].includes(item.status)), [segment, subscriptions]);
  return <DashboardLayout allowedRole="CUSTOMER"><div className="mx-auto max-w-7xl space-y-8 p-4 sm:p-7">
    <section className="overflow-hidden rounded-[30px] bg-gradient-to-br from-emerald-800 to-teal-700 p-6 text-white shadow-xl sm:p-9"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="text-xs font-black uppercase tracking-[.22em] text-emerald-200">Recurring essentials</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">My subscriptions</h1><p className="mt-3 max-w-2xl leading-7 text-emerald-100">Fund a full plan on the first verified delivery or fund the next seven deliveries weekly. Funded stops always show ₹0 due.</p></div><a href="#available-plans" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-5 font-black text-emerald-800"><Plus className="h-5 w-5" /> New subscription</a></div></section>
    <section><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex max-w-full gap-1 overflow-x-auto rounded-2xl bg-white p-1.5 shadow-sm">{Object.keys(segments).map((name) => <button key={name} onClick={() => setSegment(name)} className={`min-h-10 rounded-xl px-4 text-sm font-black ${segment === name ? 'bg-emerald-100 text-emerald-800' : 'text-slate-500 hover:bg-slate-50'}`}>{name}</button>)}</div><button onClick={() => void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 font-bold text-slate-700"><RefreshCw className="h-4 w-4" /> Refresh</button></div>
      {loading ? <div className="flex min-h-52 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-emerald-700" /></div> : filtered.length ? <div className="mt-5 grid gap-4 lg:grid-cols-2">{filtered.map((item) => { const total=Number(item.planVersion?.totalDeliveries || item.completedDeliveries + item.remainingFundedDeliveries || 1); const progress=Math.min(100,Math.round(Number(item.completedDeliveries||0)/total*100)); return <Link key={item.id} href={`/shop/subscriptions/${item.id}`} className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm transition hover:border-emerald-300 hover:shadow-md"><div className="flex items-start gap-4"><div className="flex h-16 w-16 items-center justify-center overflow-hidden rounded-2xl bg-emerald-50">{item.plan?.imageUrl ? <img src={item.plan.imageUrl} alt="" className="h-full w-full object-contain"/>:<CalendarClock className="h-7 w-7 text-emerald-700"/>}</div><div className="min-w-0 flex-1"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black uppercase text-emerald-700">{String(item.status).replaceAll('_',' ')}</span><h2 className="mt-2 truncate text-xl font-black text-slate-900">{item.plan?.name}</h2><p className="mt-1 text-sm text-slate-500">{item.fundingCycle === 'WEEKLY' ? 'Weekly cash funding' : 'Full-plan cash funding'}</p></div><ChevronRight className="h-5 w-5 text-slate-400"/></div><div className="mt-5 flex justify-between text-sm font-bold text-slate-600"><span>{item.completedDeliveries} of {total} delivered</span><span className="text-emerald-700">{progress}%</span></div><div className="mt-2 h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600" style={{ width: `${progress}%` }} /></div><div className="mt-5 grid grid-cols-3 gap-2"><Metric icon={<CalendarClock className="h-4 w-4"/>} label="Next" value={formatDate(item.nextDeliveryDate)}/><Metric icon={<WalletCards className="h-4 w-4"/>} label="Cash due" value={formatPaise(item.amountDuePaise)}/><Metric icon={<PauseCircle className="h-4 w-4"/>} label="Funded left" value={String(item.remainingFundedDeliveries)}/></div></Link>; })}</div> : <div className="mt-5 rounded-[24px] border border-dashed border-slate-300 bg-white p-12 text-center"><CalendarClock className="mx-auto h-10 w-10 text-slate-400"/><h2 className="mt-4 text-xl font-black text-slate-800">No {segment.toLowerCase()} subscriptions</h2><p className="mt-2 text-slate-500">Published plans are available below.</p></div>}
    </section>
    <section id="available-plans"><div className="mb-5"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Discover</p><h2 className="mt-2 text-2xl font-black text-slate-900">Available plans</h2></div>{plans.length ? <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{plans.map((plan) => <SubscriptionPlanCard key={plan.id} plan={plan}/>)}</div> : <div className="rounded-3xl bg-white p-10 text-center text-slate-500">No active plans are published yet.</div>}</section>
  </div></DashboardLayout>;
}
function Metric({ icon,label,value }:{icon:React.ReactNode;label:string;value:string}) { return <div className="rounded-2xl bg-slate-50 p-3 text-slate-600"><div className="text-emerald-700">{icon}</div><p className="mt-2 text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 truncate text-xs font-black text-slate-800">{value}</p></div>; }
